from django.contrib import admin
from .models import PricingDBSite, PricingDBBuilding, PricingDBBuildingSurface, PricingDBZone, PrincingDBProjectPrimInfos, PrincingDBProjectSubPricing, PrincingDBProjectSubPricingContainedBuilding, PrincingDBProjectSubPricingContainedZone, PrincingDBProjectSubPricingTrade, PrincingDBProjectSubPricingSubTrade, PrincingDBProjectSubPricingSubTradeCompanyOffer, PrincingDBProjectSubPricingSubSubTradeGroup, PrincingDBProjectSubPricingSubSubTrade, PrincingDBProjectPriceDetail, PricingDBZoneSurface, PricingDBSiteSurface, Question, Choice

# Register your models here.

admin.site.register(model_or_iterable=[PricingDBSite, PricingDBBuilding, PricingDBBuildingSurface, PricingDBZone, PrincingDBProjectPrimInfos, PrincingDBProjectSubPricing, PrincingDBProjectSubPricingContainedBuilding, PrincingDBProjectSubPricingContainedZone, PrincingDBProjectSubPricingTrade, PrincingDBProjectSubPricingSubTrade, PrincingDBProjectSubPricingSubTradeCompanyOffer, PrincingDBProjectSubPricingSubSubTradeGroup, PrincingDBProjectSubPricingSubSubTrade, PrincingDBProjectPriceDetail, PricingDBZoneSurface, PricingDBSiteSurface, Question, Choice])
