# Generated by Django 5.1.2 on 2024-10-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingDBBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('construction_date', models.DateTimeField(verbose_name='Construction Date')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBBuildingSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0.0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbbuilding')),
            ],
        ),
        migrations.AddField(
            model_name='pricingdbbuilding',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite'),
        ),
        migrations.CreateModel(
            name='PricingDBSiteSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0.0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classement', models.CharField(max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbbuilding')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBHabitationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitation_type', models.CharField(default='', max_length=200)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBERTInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=200)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBERPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_type', models.CharField(default='', max_length=200)),
                ('erp_category', models.IntegerField(default='0')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone')),
            ],
        ),
        migrations.CreateModel(
            name='PricingDBZoneSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0.0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectPrimInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specific_surface', models.FloatField(default=0.0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectContainedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectpriminfos')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectContainedBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectpriminfos')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectpriminfos')),
            ],
        ),
    ]
