# Generated by Django 5.1.2 on 2024-10-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pricingdbbuilding_pricingdbsite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincingDBProjectSubSubTradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectSubSubTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubsubtradegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectPriceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measure_unity', models.CharField(max_length=200)),
                ('unity_price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubsubtradegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PrincingDBProjectSubTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojecttrade')),
            ],
        ),
        migrations.AddField(
            model_name='princingdbprojectsubsubtradegroup',
            name='sub_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubtrade'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
