# Generated by Django 5.1.2 on 2024-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_popdbavailablesussubtradegroup_popdbbuilding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdbbuildingsurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='popdbsitesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='popdbzonesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbbuildingsurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbsitesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], max_length=200),
        ),
    ]
