# Generated by Django 5.1.2 on 2024-10-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_popdbbuildingsurface_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdbsite',
            name='id_in_excel',
            field=models.IntegerField(default=100),
        ),
    ]
