# Generated by Django 5.1.2 on 2024-10-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_pricingdbsite_id_in_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdberpinfo',
            name='erp_category',
            field=models.IntegerField(default=0),
        ),
    ]
