# Generated by Django 5.1.2 on 2024-10-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_popdberpinfo_erp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbsite',
            name='id_in_excel',
            field=models.IntegerField(default=102),
        ),
    ]
