# Generated by Django 5.1.2 on 2024-10-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_pricingdbsite_id_in_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdbbuilding',
            name='excel_ref',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingdbsite',
            name='excel_ref',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingdbzone',
            name='excel_ref',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='princingdbprojectsubpricingsubsubtradegroup',
            name='company_ref',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='princingdbprojectsubpricingsubsubtradegroup',
            name='excel_p_ref',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='princingdbprojectsubpricingsubsubtradegroup',
            name='excel_ref',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='princingdbprojectsubpricingsubtradecompanyoffer',
            name='excel_p_ref',
            field=models.CharField(default='', max_length=200),
        ),
    ]
