# Generated by Django 5.1.2 on 2024-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_pricingdbbuilding_excel_ref_pricingdbsite_excel_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='construction_date',
            field=models.DateTimeField(default='01/01/1900', verbose_name='Construction Date'),
        ),
    ]
