# Generated by Django 5.1.2 on 2024-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_pricingdbbuilding_construction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='construction_date',
            field=models.DateTimeField(default='0001-01-01 00:00', verbose_name='Construction Date'),
        ),
    ]
