# Generated by Django 5.1.2 on 2024-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_pricingdbbuilding_construction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popdbertinfo',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='popdbhabitationinfo',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='pricingdberpinfo',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='pricingdbertinfo',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='pricingdbhabitationinfo',
            name='zone',
        ),
        migrations.RenameField(
            model_name='popdbzone',
            old_name='classement',
            new_name='classiffication',
        ),
        migrations.RenameField(
            model_name='pricingdbzone',
            old_name='classement',
            new_name='classiffication',
        ),
        migrations.AddField(
            model_name='popdbzone',
            name='category',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='popdbzone',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingdbzone',
            name='category',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='pricingdbzone',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='POPDBERPInfo',
        ),
        migrations.DeleteModel(
            name='POPDBERTInfo',
        ),
        migrations.DeleteModel(
            name='POPDBHabitationInfo',
        ),
        migrations.DeleteModel(
            name='PricingDBERPInfo',
        ),
        migrations.DeleteModel(
            name='PricingDBERTInfo',
        ),
        migrations.DeleteModel(
            name='PricingDBHabitationInfo',
        ),
    ]
