# Generated by Django 5.1.2 on 2024-10-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_popdbertinfo_zone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popdbzone',
            old_name='classiffication',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='pricingdbzone',
            old_name='classiffication',
            new_name='classification',
        ),
    ]
