# Generated by Django 5.1.2 on 2024-10-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rename_classiffication_popdbzone_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdbbuilding',
            name='construction_date',
            field=models.DateTimeField(default='1650-01-01 00:00', verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='construction_date',
            field=models.DateTimeField(default='1650-01-01 00:00', verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='pricingdbbuildingsurface',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
