# Generated by Django 5.1.2 on 2024-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_popdbbuilding_construction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdbbuilding',
            name='construction_date',
            field=models.DateField(default='1650-01-01', verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='popdbprojectpriminfos',
            name='project_date',
            field=models.DateField(verbose_name='Pricings Project Date'),
        ),
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='construction_date',
            field=models.DateField(default='1650-01-01', verbose_name='Construction Date'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectpriminfos',
            name='project_date',
            field=models.DateField(verbose_name='Project Date'),
        ),
    ]
