# Generated by Django 5.1.2 on 2024-10-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_popdbbuilding_construction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='princingdbprojectpriminfos',
            name='project_date',
            field=models.DateField(default='1650-01-01', verbose_name='Project Date'),
        ),
    ]
