# Generated by Django 5.1.2 on 2024-10-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_princingdbprojectpriminfos_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdbbuilding',
            name='construction_date',
            field=models.CharField(default='XXX', max_length=200),
        ),
        migrations.AlterField(
            model_name='popdbprojectpriminfos',
            name='project_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='construction_date',
            field=models.CharField(default='XXX', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectpriminfos',
            name='project_date',
            field=models.CharField(default='XXX', max_length=200),
        ),
    ]
