# Generated by Django 5.1.2 on 2024-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_popdbbuilding_construction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbbuildingsurface',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbsitesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbzone',
            name='classification',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbzone',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='name',
            field=models.CharField(choices=[('SHAB', 'Shab'), ('SHON', 'Shon'), ('SDP', 'Sdp'), ('SUB', 'Sub'), ('SUN', 'Sun'), ('SuperSTRUnknownType', 'Superstrunknowntype'), ('CoveredParking', 'Coveredparking'), ('InfraSTRUnknownType', 'Infrastrunknowntype'), ('TotalExtern', 'Totalextern'), ('GreenAera', 'Greenaera'), ('ExternalParking', 'Externalparking')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectpriminfos',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricing',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingcontainedbuilding',
            name='building_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingcontainedzone',
            name='zone_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubsubtrade',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubtrade',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingtrade',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingtrade',
            name='used_index_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
