# Generated by Django 5.1.2 on 2024-10-28 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_pricingdbbuilding_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone'),
        ),
    ]
