# Generated by Django 5.1.2 on 2024-10-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_pricingdbzonesurface_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone'),
        ),
    ]
