# Generated by Django 5.1.2 on 2024-10-28 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_pricingdbzonesurface_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdbbuilding',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.popdbsite'),
        ),
        migrations.AlterField(
            model_name='popdbbuildingsurface',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.popdbbuilding'),
        ),
        migrations.AlterField(
            model_name='popdbsitesurface',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.popdbsite'),
        ),
        migrations.AlterField(
            model_name='popdbzone',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.popdbbuilding'),
        ),
        migrations.AlterField(
            model_name='popdbzonesurface',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.popdbzone'),
        ),
        migrations.AlterField(
            model_name='pricingdbbuilding',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite'),
        ),
        migrations.AlterField(
            model_name='pricingdbbuildingsurface',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbbuilding'),
        ),
        migrations.AlterField(
            model_name='pricingdbsitesurface',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite'),
        ),
        migrations.AlterField(
            model_name='pricingdbzone',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbbuilding'),
        ),
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='zone',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectpricedetail',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingsubsubtradegroup'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectpriminfos',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbsite'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricing',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectpriminfos'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingcontainedbuilding',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricing'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingcontainedzone',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingcontainedbuilding'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubsubtrade',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingsubsubtradegroup'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubsubtradegroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingsubtradecompanyoffer'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubtrade',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingtrade'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingsubtradecompanyoffer',
            name='sub_trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricingsubtrade'),
        ),
        migrations.AlterField(
            model_name='princingdbprojectsubpricingtrade',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.princingdbprojectsubpricing'),
        ),
    ]
