# Generated by Django 5.1.2 on 2024-10-28 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_popdbbuilding_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdbzonesurface',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pricingdbzone'),
        ),
    ]
