# Generated by Django 5.1.2 on 2025-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='name',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
