# Generated by Django 5.1.2 on 2025-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0002_etude_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='assistant_id',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
