# Generated by Django 5.1.2 on 2025-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0003_etude_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='assistant_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
