# Generated by Django 5.1.2 on 2025-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0005_alter_etude_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='name',
            field=models.CharField(choices=[('Incendie', 'Incendie'), ('ICPE', 'ICPE'), ('Autre', 'Autre')], max_length=1000),
        ),
    ]
