# Generated by Django 5.1.2 on 2025-02-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0007_alter_etude_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='json_db',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='etude',
            name='json_db_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
