# Generated by Django 5.1.2 on 2025-02-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiecobe', '0008_etude_json_db_etude_json_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='json_db',
        ),
        migrations.RemoveField(
            model_name='project',
            name='json_db_id',
        ),
    ]
